Email notification
wolox-training/nz-rails pull request #17
Opened 2017-11-17 17:32 UTC by nicozar95

## Summary 
* Added email notification when a rent is created
* Sidekiq implementation to perform asyncronic mail send

## Trello
https://trello.com/c/obwTR6QP/11-mandar-email-al-usuario-cuando-se-crea-un-rent

2017-11-23 16:10 UTC, juanisierra requested changes

2017-11-23 16:10 UTC, juanisierra commented on app/workers/async_mailer_worker.rb
> +  include Sidekiq::Worker
Do you use this worker?

2017-11-23 16:10 UTC, juanisierra commented on config/environments/development.rb
> +##  config.action_mailer.delivery_method = :smtp
Remove comments please

2017-11-23 16:10 UTC, juanisierra commented on spec/fixtures/user_mailer/rent_finished_notification
> +UserMailer#rent_finished_notification
Do you use this for something?

2017-11-24 12:08 UTC, nicozar95 commented on app/workers/async_mailer_worker.rb
> +  include Sidekiq::Worker
Yes

2017-11-24 13:13 UTC, juanisierra approved these changes

2017-11-24 13:14 UTC, merged