Added authentication configuration for the api implementation
wolox-training/nz-rails pull request #8
Opened 2017-11-10 18:33 UTC by nicozar95

## Summary
* Added authentication configuration for the api implementation

## Trello
https://trello.com/c/xVCvpxxM/26-implementar-autenticaci%C3%B3n

2017-11-13 20:24 UTC, juanisierra requested changes

2017-11-13 20:24 UTC, juanisierra commented on app/controllers/api/v1/users_controller.rb
> +        render json: '', status: :ok
If the user can't be created it should return and error. Add the error cases please

2017-11-13 20:24 UTC, juanisierra commented on db/migrate/20171110172056_devise_create_users.rb
> +      t.string :locale, null: false
Remember that you shouldn't edit migrations, you should create  a new one that edits the schema

2017-11-13 20:24 UTC, juanisierra commented on db/migrate/XXXX_add_verification_code_to_users.rb
> +class AddVerificationCodeToUsers < ActiveRecord::Migration[5.0]
Please rename this file and change XXXX for a valid timestamp

2017-11-15 13:34 UTC, juanisierra requested changes

2017-11-15 13:34 UTC, juanisierra commented on app/controllers/api/v1/users_controller.rb
> +          render json: { errors: @user.errors.full_messages }
Please add a Bad Request status when returning

2017-11-16 14:36 UTC, juanisierra approved these changes
Check that gem and merge

2017-11-16 14:36 UTC, juanisierra commented on Gemfile
> +gem 'versionist'
What do you need this gem for?

2017-11-16 16:52 UTC, nicozar95 commented on Gemfile
> +gem 'versionist'
It is for testing

2017-11-21 11:54 UTC, merged